# 1. Configuración de conexión a la base de datos MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/krama_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 2. Configuración de JPA y Hibernate (La magia de los datos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Configuración para enviar correos electrónicos (SMTP de Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kramapracticasjoyfe@gmail.com
spring.mail.password=uyhq fkwc qnqv sxeg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true